// FR8X-CON Application Constants

export const APP_NAME = "FR8X-CON" as const;
export const APP_DESCRIPTION = "Enterprise Freight Reverse-Auction & Logistics Collaboration Platform" as const;

// Routes
export const ROUTES = {
  // Auth
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  TERMS: "/terms",

  // Dashboard
  FEEDS: "/feeds",
  PROFILE: "/profile",
  PROFILE_VIEW: (userId: string) => `/profile/${userId}` as const,
  SAVED_POSTS: "/saved-posts",
  CONTACTS: "/contacts",
  MESSAGES: "/messages",
  FOLLOWED_TAGS: "/followed-tags",
  COMPANY_PAGE: "/company",
  COMPANY_VIEW: (companyId: string) => `/company/${companyId}` as const,
  SEARCH: "/search",

  // Auctions
  AUCTIONS: "/auctions",
  AUCTION_CREATE: "/auctions/create",
  AUCTION_DETAIL: (id: string) => `/auctions/${id}` as const,
  AUCTION_BID: (id: string) => `/auctions/${id}/bid` as const,

  // Rates
  RATES: "/rates",

  // Awards & Blacklist
  AWARDS: "/awards",
  BLACKLIST: "/blacklist",

  // Jobs
  JOBS: "/jobs",

  // Admin / GodMode
  GODMODE: "/godmode",
  GODMODE_LOGIN: "/godmode/login",
  GODMODE_USERS: "/godmode/users",
  GODMODE_COMPANIES: "/godmode/companies",
  GODMODE_AUCTIONS: "/godmode/auctions",
  GODMODE_ADS: "/godmode/ads",
  GODMODE_AWARDS: "/godmode/awards",
  GODMODE_BLACKLIST: "/godmode/blacklist",
  GODMODE_MODERATION: "/godmode/moderation",
  GODMODE_VERIFICATION: "/godmode/verification",
  GODMODE_BILLING: "/godmode/billing",
  GODMODE_AUDIT: "/godmode/audit",
  GODMODE_SETTINGS: "/godmode/settings",
  GODMODE_LOCATIONS: "/godmode/locations",
  GODMODE_BACKUPS: "/godmode/backups",
} as const;

// Firestore Collections
export const COLLECTIONS = {
  USERS: "users",
  PROFILES: "profiles",
  COMPANIES: "companies",
  POSTS: "posts",
  COMMENTS: "comments",
  LIKES: "likes",
  BOOKMARKS: "bookmarks",
  AWARDS: "awards",
  BLACKLISTS: "blacklists",
  AUCTIONS: "auctions",
  AUCTION_ITEMS: "auctionItems",
  AUCTION_PARTICIPANTS: "auctionParticipants",
  BIDS: "bids",
  LIVE_RANKS: "liveRanks",
  RATES: "rates",
  CURRENCIES: "currencies",
  NOTIFICATIONS: "notifications",
  LOGS: "logs",
  AUDIT: "audit",
  SETTINGS: "settings",
  JOBS: "jobs",
  JOB_APPLICATIONS: "jobApplications",
  TRANSACTIONS: "transactions",
  CONNECTIONS: "connections",
  LOCATIONS: "locations",
  BACKUPS: "backups",
  LOCATION_AUDIT: "location_audit",
  ADS: "ads",
  OTPS: "otps",
  INVOICES: "invoices",
  RECEIPTS: "receipts",
  STAMPS: "stamps",
  PUSH_TOKENS: "push_tokens",
  TAGS: "tags",
} as const;


// Bid constraints
export const BID_MAX_SUBMISSIONS = 5;

// Industry & Service Tags (spec page 2)
export const INDUSTRY_TAGS = [
  "NVOCC",
  "Freight Forwarding",
  "FCL",
  "LCL",
  "Ocean Freight",
  "Customs Clearance",
  "Dangerous Goods",
  "Cross-border Trade",
  "Air Freight",
  "Inland Haulage",
  "Warehousing",
  "Cold Chain",
  "Project Cargo",
  "Multimodal",
] as const;

// User Roles & Business Verticals (spec page 2 & 11)
export const USER_ROLES = [
  { value: "freight_forwarder", label: "Freight Forwarder" },
  { value: "mlo", label: "Shipping Line / MLO" },
  { value: "exporter", label: "Exporter" },
  { value: "importer", label: "Importer" },
  { value: "cha", label: "CHA (Custom House Agent)" },
  { value: "customs_broker", label: "Customs Broker" },
  { value: "transporter", label: "Transporter" },
  { value: "warehouse", label: "Warehouse Operator" },
  { value: "nvocc", label: "NVOCC" },
  { value: "shipping_agent", label: "Shipping Agent" },
] as const;

// Feed categories (spec page 3 — extended)
export const FEED_CATEGORIES = [
  { value: "all", label: "All" },
  { value: "nvocc", label: "NVOCC" },
  { value: "freight_forwarding", label: "Freight Forwarding" },
  { value: "project_cargo", label: "Project Cargo" },
  { value: "fcl", label: "FCL" },
  { value: "lcl", label: "LCL" },
  { value: "air", label: "Air" },
  { value: "ocean", label: "Ocean" },
  { value: "road", label: "Road" },
  { value: "customs", label: "Customs" },
  { value: "warehousing", label: "Warehousing" },
  { value: "cold_chain", label: "Cold Chain" },
  { value: "multimodal", label: "Multimodal" },
  { value: "rig_to_destination", label: "Rig to destination (sea/air)" },
] as const;

// Feed sort options
export const FEED_SORT_OPTIONS = [
  { value: "latest", label: "Latest" },
  { value: "popular", label: "Popular" },
  { value: "following", label: "Following" },
  { value: "my_posts", label: "My Posts" },
] as const;

// Container & Equipment sizes (spec page 8 & multi-modal engine)
export const CONTAINER_SIZES = [
  { value: "20ft", label: "20' Standard (20'DV)" },
  { value: "40ft", label: "40' Standard (40'DV)" },
  { value: "40ft_hc", label: "40' High Cube (40'HC)" },
  { value: "45ft", label: "45' High Cube (45'HC)" },
  { value: "open_top", label: "Open Top Container (OT)" },
  { value: "flat_rack", label: "Flat Rack Container (FR)" },
  { value: "platform", label: "Platform Container" },
  { value: "reefer", label: "Reefer Container (RF)" },
  { value: "tank_container", label: "Tank Container" },
  { value: "iso_tank", label: "ISO Tank Container" },
  { value: "special_equipment", label: "Special / Customized Equipment" },
] as const;

export const INCOTERMS_LIST = [
  "EXW",
  "FCA",
  "FAS",
  "FOB",
  "CFR",
  "CIF",
  "CPT",
  "CIP",
  "DAP",
  "DPU",
  "DDP",
] as const;

// Membership tiers (spec page 2 — Trial = 2 days free access)
export const MEMBERSHIP_TIERS = [
  {
    id: "trial",
    name: "Trial",
    priceINR: 0,
    priceUSD: 0,
    period: "2 days",
    features: ["Verified badge", "RFQ posting", "0 saved searches"],
    comingSoon: false,
  },
  {
    id: "basic",
    name: "Basic",
    priceINR: 1499,
    priceUSD: 25,
    period: "mo",
    features: [
      "Verified badge",
      "Bidding and rates posting",
      "Unlimited rates search and requests",
    ],
    comingSoon: false,
  },
  {
    id: "premium",
    name: "Premium",
    priceINR: null,
    priceUSD: null,
    period: null,
    label: "Custom",
    features: [
      "Multi-seat access",
      "Dedicated account manager",
      "API integration",
    ],
    comingSoon: true,
  },
] as const;

// Job posting constants (spec page 6)
export const JOB_INDUSTRIES = [
  "Logistics",
  "Freight",
  "NVOCC",
  "Shipping",
  "Customs",
  "Warehousing",
  "Supply Chain",
] as const;

export const JOB_EMPLOYMENT_TYPES = [
  "Full-Time",
  "Part-Time",
  "Contract",
  "Internship",
  "Temporary",
] as const;

export const JOB_EXPERIENCE_LEVELS = [
  "Fresher",
  "1-2 Yrs",
  "3-5 Yrs",
  "5-10 Yrs",
  "10+ Yrs",
] as const;

export const JOB_CARGO_TYPES = [
  "FCL",
  "LCL",
  "Air",
  "Ocean",
  "Project Cargo",
  "Breakbulk",
  "Reefer",
  "DG",
] as const;

export const JOB_CATEGORIES = [
  "Operations",
  "Sales",
  "Pricing",
  "Documentation",
  "Customs",
  "Warehouse",
  "HR",
  "Finance",
  "IT",
] as const;

export const JOB_APPLY_VIA = ["Portal", "Email", "External Link"] as const;
export const JOB_WORK_MODES = ["On-site", "Hybrid", "Remote"] as const;
export const JOB_SALARY_TYPES = ["Monthly", "Annual"] as const;
export const JOB_PREFERRED_SOFTWARE = ["CargoWise", "SAP", "ERP", "Tally", "MS Office", "Other"] as const;
export const JOB_LANGUAGES = ["English", "Hindi", "Other"] as const;

export const JOB_SUBMISSION_FEE_INR = 499;
export const JOB_VALIDITY_DAYS = 2;
export const JOB_RENEWAL_FEE_INR = 499;

// Mandatory rate heads (spec page 8)
export const MANDATORY_RATE_HEADS = [
  "Ocean Freight Rate (All-in)",
  "Terminal Handling Charges - Origin",
  "Terminal Handling Charges - Destination",
  "Documentation Charges",
  "Customs Clearance Charges - Origin",
  "Customs Clearance Charges - Destination",
  "Other Surcharges (specify)",
  "Inland Transportation - Origin",
  "Inland Transportation - Destination",
  "Warehousing / Storage Charges",
  "Cargo Insurance Charges",
  "Packing / Crating Charges",
  "BAF / CAF / THC / ISPS / other surcharges",
] as const;

// Pagination defaults
export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;

// Currency cache TTL (seconds)
export const CURRENCY_CACHE_TTL = 300; // 5 minutes

// Responsive breakpoints (matching Tailwind)
export const BREAKPOINTS = {
  SM: 640,
  MD: 768,
  LG: 1024,
  XL: 1280,
  "2XL": 1536,
} as const;

// Global Ports & Locations Seeding Data (Sea, Air, Rail, Dry, ICD, CFS, Warehouses, Borders, etc.)
export const LOCATION_SEED_DATA = [
  // Sea Ports
  {
    fr8xLocationId: "LOC-UN-INNSA-001",
    code: "INNSA",
    name: "Nhava Sheva Port (JNPT)",
    country: "India",
    countryCode: "IN",
    state: "Maharashtra",
    city: "Mumbai",
    unlocode: "INNSA",
    portCode: "INNSA",
    type: "sea",
    transportModes: ["ocean", "multimodal"],
    postalCode: "400707",
    status: "approved",
    source: "seed",
    coordinates: { lat: 18.95, lng: 72.95 },
    timezone: "GMT+5:30",
    customsOffice: "Jawaharlal Nehru Custom House (JNCH)",
    portAuthority: "Jawaharlal Nehru Port Authority",
    terminalOperator: "DP World / APM Terminals / PSA",
    aliases: ["Mumbai", "JNPT", "Nhava Sheva", "Jawaharlal Nehru Port"],
    searchFrequency: 15
  },
  {
    fr8xLocationId: "LOC-UN-INMUN-002",
    code: "INMUN",
    name: "Mundra Port",
    country: "India",
    countryCode: "IN",
    state: "Gujarat",
    city: "Mundra",
    unlocode: "INMUN",
    portCode: "INMUN",
    type: "sea",
    transportModes: ["ocean", "multimodal"],
    postalCode: "370421",
    status: "approved",
    source: "seed",
    coordinates: { lat: 22.74, lng: 69.70 },
    timezone: "GMT+5:30",
    customsOffice: "Mundra Custom House",
    portAuthority: "Gujarat Maritime Board",
    terminalOperator: "Adani Ports & SEZ",
    aliases: ["Mundra Port", "Adani Mundra", "MUNDRA"],
    searchFrequency: 12
  },
  {
    fr8xLocationId: "LOC-UN-SGSIN-003",
    code: "SGSIN",
    name: "Singapore Port",
    country: "Singapore",
    countryCode: "SG",
    state: "Singapore",
    city: "Singapore",
    unlocode: "SGSIN",
    portCode: "SGSIN",
    type: "sea",
    transportModes: ["ocean", "multimodal"],
    postalCode: "099253",
    status: "approved",
    source: "seed",
    coordinates: { lat: 1.35, lng: 103.82 },
    timezone: "GMT+8:00",
    customsOffice: "Singapore Customs Office",
    portAuthority: "Maritime and Port Authority of Singapore",
    terminalOperator: "PSA Singapore",
    aliases: ["SIN", "Singapore Port", "PSA Singapore", "Keppel Terminal"],
    searchFrequency: 20
  },
  {
    fr8xLocationId: "LOC-UN-NLRTM-004",
    code: "NLRTM",
    name: "Port of Rotterdam",
    country: "Netherlands",
    countryCode: "NL",
    state: "South Holland",
    city: "Rotterdam",
    unlocode: "NLRTM",
    portCode: "NLRTM",
    type: "sea",
    transportModes: ["ocean", "multimodal"],
    postalCode: "3002AP",
    status: "approved",
    source: "seed",
    coordinates: { lat: 51.92, lng: 4.48 },
    timezone: "GMT+1:00",
    customsOffice: "Rotterdam Customs",
    portAuthority: "Port of Rotterdam Authority",
    terminalOperator: "ECT Delta Terminal",
    aliases: ["Roterdam", "Rotterdam Port", "Europort"],
    searchFrequency: 18
  },
  {
    fr8xLocationId: "LOC-UN-USLAX-005",
    code: "USLAX",
    name: "Port of Los Angeles",
    country: "United States",
    countryCode: "US",
    state: "California",
    city: "Los Angeles",
    unlocode: "USLAX",
    portCode: "USLAX",
    type: "sea",
    transportModes: ["ocean", "multimodal"],
    postalCode: "90731",
    status: "approved",
    source: "seed",
    coordinates: { lat: 33.74, lng: -118.26 },
    timezone: "GMT-8:00",
    customsOffice: "US Customs & Border Protection LA",
    portAuthority: "Los Angeles Harbor Department",
    terminalOperator: "APM Terminals / Fenix Marine",
    aliases: ["LA Port", "Los Angeles Port", "Port of LA", "LAX"],
    searchFrequency: 10
  },
  {
    fr8xLocationId: "LOC-UN-AEJEA-006",
    code: "AEJEA",
    name: "Jebel Ali Port",
    country: "UAE",
    countryCode: "AE",
    state: "Dubai",
    city: "Dubai",
    unlocode: "AEJEA",
    portCode: "AEJEA",
    type: "sea",
    transportModes: ["ocean", "multimodal"],
    postalCode: "17000",
    status: "approved",
    source: "seed",
    coordinates: { lat: 25.01, lng: 55.06 },
    timezone: "GMT+4:00",
    customsOffice: "Dubai Customs Jebel Ali",
    portAuthority: "DP World UAE",
    terminalOperator: "DP World",
    aliases: ["Jebel Ali", "Dubai Port", "DP World Jebel Ali"],
    searchFrequency: 14
  },
  {
    fr8xLocationId: "LOC-UN-DEHAM-007",
    code: "DEHAM",
    name: "Hamburg Port",
    country: "Germany",
    countryCode: "DE",
    state: "Hamburg",
    city: "Hamburg",
    unlocode: "DEHAM",
    portCode: "DEHAM",
    type: "sea",
    transportModes: ["ocean", "multimodal"],
    postalCode: "20457",
    status: "approved",
    source: "seed",
    coordinates: { lat: 53.55, lng: 9.99 },
    timezone: "GMT+1:00",
    customsOffice: "Hamburg Zollamt",
    portAuthority: "Hamburg Port Authority",
    terminalOperator: "HHLA / Eurogate",
    aliases: ["Hamburg Port", "HHLA", "Elbe Port"],
    searchFrequency: 8
  },

  // Air Ports
  {
    fr8xLocationId: "LOC-AIR-BOM-008",
    code: "BOM",
    name: "Chhatrapati Shivaji Maharaj International Airport",
    country: "India",
    countryCode: "IN",
    state: "Maharashtra",
    city: "Mumbai",
    unlocode: "INBOM",
    iataCode: "BOM",
    icaoCode: "VABB",
    type: "air",
    transportModes: ["air", "multimodal"],
    postalCode: "400099",
    status: "approved",
    source: "seed",
    coordinates: { lat: 19.09, lng: 72.87 },
    timezone: "GMT+5:30",
    customsOffice: "Air Cargo Complex Sahar (ACC)",
    portAuthority: "Airports Authority of India / Adani",
    terminalOperator: "Mumbai International Airport Ltd (MIAL)",
    aliases: ["BOM", "Mumbai Airport", "CSIA", "Sahar Airport"],
    searchFrequency: 25
  },
  {
    fr8xLocationId: "LOC-AIR-DEL-009",
    code: "DEL",
    name: "Indira Gandhi International Airport",
    country: "India",
    countryCode: "IN",
    state: "Delhi",
    city: "Delhi",
    unlocode: "INDEL",
    iataCode: "DEL",
    icaoCode: "VIDP",
    type: "air",
    transportModes: ["air", "multimodal"],
    postalCode: "110037",
    status: "approved",
    source: "seed",
    coordinates: { lat: 28.56, lng: 77.10 },
    timezone: "GMT+5:30",
    customsOffice: "Air Cargo Complex Delhi (ACC)",
    portAuthority: "Airports Authority of India / GMR",
    terminalOperator: "Delhi International Airport Ltd (DIAL)",
    aliases: ["DEL", "Delhi Airport", "IGIA", "Palam Airport"],
    searchFrequency: 22
  },
  {
    fr8xLocationId: "LOC-AIR-DXB-010",
    code: "DXB",
    name: "Dubai International Airport",
    country: "UAE",
    countryCode: "AE",
    state: "Dubai",
    city: "Dubai",
    unlocode: "AEDXB",
    iataCode: "DXB",
    icaoCode: "OMDB",
    type: "air",
    transportModes: ["air", "multimodal"],
    postalCode: "2525",
    status: "approved",
    source: "seed",
    coordinates: { lat: 25.25, lng: 55.36 },
    timezone: "GMT+4:00",
    customsOffice: "Dubai Airport Customs",
    portAuthority: "Dubai Airports Company",
    terminalOperator: "dnata Cargo",
    aliases: ["DXB", "Dubai Airport", "Dnata Cargo"],
    searchFrequency: 18
  },
  {
    fr8xLocationId: "LOC-AIR-SIN-011",
    code: "SIN",
    name: "Singapore Changi Airport",
    country: "Singapore",
    countryCode: "SG",
    state: "Singapore",
    city: "Singapore",
    unlocode: "SGSIN",
    iataCode: "SIN",
    icaoCode: "WSSS",
    type: "air",
    transportModes: ["air", "multimodal"],
    postalCode: "918146",
    status: "approved",
    source: "seed",
    coordinates: { lat: 1.36, lng: 103.99 },
    timezone: "GMT+8:00",
    customsOffice: "Changi Air Cargo Customs",
    portAuthority: "Changi Airport Group",
    terminalOperator: "SATS Cargo / dnata",
    aliases: ["SIN", "Changi Airport", "Singapore Airport", "Changi Cargo"],
    searchFrequency: 24
  },
  {
    fr8xLocationId: "LOC-AIR-LAX-012",
    code: "LAX",
    name: "Los Angeles International Airport",
    country: "United States",
    countryCode: "US",
    state: "California",
    city: "Los Angeles",
    unlocode: "USLAX",
    iataCode: "LAX",
    icaoCode: "KLAX",
    type: "air",
    transportModes: ["air", "multimodal"],
    postalCode: "90045",
    status: "approved",
    source: "seed",
    coordinates: { lat: 34.05, lng: -118.24 },
    timezone: "GMT-8:00",
    customsOffice: "US CBP LAX Cargo",
    portAuthority: "Los Angeles World Airports (LAWA)",
    terminalOperator: "LAX Cargo Terminals",
    aliases: ["LAX", "LA Airport", "Los Angeles Airport"],
    searchFrequency: 17
  },

  // ICDs / CFSs / Dry Ports
  {
    fr8xLocationId: "LOC-ICD-INTKD-013",
    code: "INTKD",
    name: "Tughlakabad ICD",
    country: "India",
    countryCode: "IN",
    state: "Delhi",
    city: "Delhi",
    unlocode: "INTKD",
    icdCode: "INTKD",
    type: "icd",
    transportModes: ["rail", "road", "ocean", "multimodal"],
    postalCode: "110020",
    status: "approved",
    source: "seed",
    coordinates: { lat: 28.50, lng: 77.29 },
    timezone: "GMT+5:30",
    customsOffice: "ICD Tughlakabad Customs Commissionerate",
    portAuthority: "Container Corporation of India (CONCOR)",
    terminalOperator: "CONCOR",
    aliases: ["Tughlakabad ICD", "ICD TKD", "TKD Depot"],
    searchFrequency: 9
  },
  {
    fr8xLocationId: "LOC-CFS-INNSA-014",
    code: "INNSA_CFS",
    name: "Nhava Sheva CFS (Dronagiri)",
    country: "India",
    countryCode: "IN",
    state: "Maharashtra",
    city: "Navi Mumbai",
    unlocode: "INNSA",
    cfsCode: "INNSA_CFS",
    type: "cfs",
    transportModes: ["ocean", "road", "multimodal"],
    postalCode: "400707",
    status: "approved",
    source: "seed",
    coordinates: { lat: 18.96, lng: 72.96 },
    timezone: "GMT+5:30",
    customsOffice: "Dronagiri Custom House",
    portAuthority: "JNPT Port Authority",
    terminalOperator: "Allcargo Logistics / Gateway Distriparks",
    aliases: ["Mumbai CFS", "JNPT CFS", "Dronagiri CFS", "Allcargo CFS"],
    searchFrequency: 7
  },
  {
    fr8xLocationId: "LOC-DRY-INWFD-015",
    code: "INWFD",
    name: "Whitefield Dry Port (Bangalore)",
    country: "India",
    countryCode: "IN",
    state: "Karnataka",
    city: "Bangalore",
    unlocode: "INWFD",
    icdCode: "INWFD",
    type: "dry",
    transportModes: ["rail", "road", "multimodal"],
    postalCode: "560066",
    status: "approved",
    source: "seed",
    coordinates: { lat: 12.98, lng: 77.75 },
    timezone: "GMT+5:30",
    customsOffice: "Bangalore ICD Customs",
    portAuthority: "CONCOR India",
    terminalOperator: "CONCOR Bangalore",
    aliases: ["Bangalore Dry Port", "Whitefield Dry Port", "ICD Whitefield"],
    searchFrequency: 5
  },

  // Rail Terminals
  {
    fr8xLocationId: "LOC-RAIL-USCHI-016",
    code: "USCHI",
    name: "Chicago Rail Terminal (Corwith)",
    country: "United States",
    countryCode: "US",
    state: "Illinois",
    city: "Chicago",
    unlocode: "USCHI",
    railCode: "USCHI_COR",
    type: "rail",
    transportModes: ["rail", "road", "multimodal"],
    postalCode: "60632",
    status: "approved",
    source: "seed",
    coordinates: { lat: 41.81, lng: -87.72 },
    timezone: "GMT-6:00",
    customsOffice: "Chicago Customs",
    portAuthority: "BNSF Railway",
    terminalOperator: "BNSF Railway",
    aliases: ["Chicago Rail Yard", "Corwith Rail Yard", "BNSF Chicago"],
    searchFrequency: 6
  },
  {
    fr8xLocationId: "LOC-RAIL-CNCKG-017",
    code: "CNCKG",
    name: "Chongqing Tuanjiecun Rail Terminal",
    country: "China",
    countryCode: "CN",
    state: "Chongqing",
    city: "Chongqing",
    unlocode: "CNCKG",
    railCode: "CNCKG_TJC",
    type: "rail",
    transportModes: ["rail", "road", "multimodal"],
    postalCode: "401331",
    status: "approved",
    source: "seed",
    coordinates: { lat: 29.62, lng: 106.36 },
    timezone: "GMT+8:00",
    customsOffice: "Chongqing Customs Office",
    portAuthority: "China Railway",
    terminalOperator: "CRIntermodal Chongqing Center",
    aliases: ["Chongqing Rail", "Yuxinou Rail", "Tuanjiecun Rail"],
    searchFrequency: 4
  },

  // Warehouses, Distribution Centers & Inland Hubs
  {
    fr8xLocationId: "LOC-WHS-INNSA-018",
    code: "INNSA_WHS",
    name: "FR8X Logistics Warehouse - Nhava Sheva",
    country: "India",
    countryCode: "IN",
    state: "Maharashtra",
    city: "Navi Mumbai",
    type: "warehouse",
    transportModes: ["road", "ocean", "multimodal"],
    postalCode: "400707",
    status: "approved",
    source: "seed",
    coordinates: { lat: 18.97, lng: 72.97 },
    timezone: "GMT+5:30",
    customsOffice: "JNPT Customs Complex Office",
    terminalOperator: "FR8X Operations India",
    aliases: ["Nhava Sheva Warehouse", "JNPT Warehouse", "FR8X Warehouse"],
    searchFrequency: 3
  },
  {
    fr8xLocationId: "LOC-HUB-USDEN-019",
    code: "USDEN_DC",
    name: "Denver Logistics Hub & Distribution Center",
    country: "United States",
    countryCode: "US",
    state: "Colorado",
    city: "Denver",
    type: "hub",
    transportModes: ["road", "rail", "multimodal"],
    postalCode: "80216",
    status: "approved",
    source: "seed",
    coordinates: { lat: 39.78, lng: -104.96 },
    timezone: "GMT-7:00",
    terminalOperator: "FR8X America Logistics",
    aliases: ["Denver DC", "Denver Logistics Center", "Rocky Mountains DC"],
    searchFrequency: 2
  },
  {
    fr8xLocationId: "LOC-HUB-INHYD-020",
    code: "INHYD_HUB",
    name: "Hyderabad Inland Distribution Hub",
    country: "India",
    countryCode: "IN",
    state: "Telangana",
    city: "Hyderabad",
    type: "hub",
    transportModes: ["road", "rail", "multimodal"],
    postalCode: "500001",
    status: "approved",
    source: "seed",
    coordinates: { lat: 17.38, lng: 78.48 },
    timezone: "GMT+5:30",
    terminalOperator: "Telangana State Logistics Corp",
    aliases: ["Hyderabad Hub", "Inland Hub Hyd", "HYD Distribution"],
    searchFrequency: 4
  },

  // Border Crossings
  {
    fr8xLocationId: "LOC-BDR-INWGH-021",
    code: "INWGH",
    name: "Wagah-Attari Border Crossing",
    country: "India",
    countryCode: "IN",
    state: "Punjab",
    city: "Amritsar",
    unlocode: "INWGH",
    type: "border",
    transportModes: ["road", "rail", "multimodal"],
    postalCode: "143001",
    status: "approved",
    source: "seed",
    coordinates: { lat: 31.60, lng: 74.57 },
    timezone: "GMT+5:30",
    customsOffice: "Attari Integrated Check Post (ICP)",
    portAuthority: "Land Ports Authority of India",
    aliases: ["Wagah Border", "Attari Border", "ICP Attari"],
    searchFrequency: 3
  }
];

